name: SevenNotes
options:
  bundleIdPrefix: com.sevennotes
  createIntermediateGroups: true
  derivedDataPath: .build
targets:
  SevenNotes-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Shared
      - path: Sources/macOS
    info:
      path: Sources/macOS/Info.plist
      properties:
        LSUIElement: true
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Sources/macOS/SevenNotes-macOS.entitlements
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
        ENABLE_HARDENED_RUNTIME:
  SevenNotes-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Shared
      - path: Sources/iOS
    info:
      path: Sources/iOS/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
