name: Heptad
options:
  bundleIdPrefix: dev.lipovoy
  createIntermediateGroups: true
  generateEmptyDirectories: true
  defaultConfig: Debug
  fileTypes:
    "icon":
      file: true
settings:
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    DEAD_CODE_STRIPPING: YES
targets:
  Heptad-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Shared
      - path: Sources/macOS
    info:
      path: Sources/macOS/Info.plist
      properties:
        LSUIElement: true
        LSApplicationCategoryType: public.app-category.productivity
    settings:
      base:
        PRODUCT_NAME: Heptad
        PRODUCT_BUNDLE_IDENTIFIER: dev.lipovoy.heptad.mac
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Sources/macOS/Heptad-macOS.entitlements
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
        ENABLE_HARDENED_RUNTIME: YES
    scheme:
      testTargets:
        - Heptad-macOSTests
  Heptad-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Shared
      - path: Sources/iOS
    info:
      path: Sources/iOS/Info.plist
      properties:
        UILaunchScreen: {}
        LSApplicationCategoryType: public.app-category.productivity
    settings:
      base:
        PRODUCT_NAME: Heptad
        PRODUCT_BUNDLE_IDENTIFIER: dev.lipovoy.heptad.ios
    scheme:
      testTargets:
        - Heptad-iOSTests
  Heptad-macOSTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/Shared
      - path: Tests/macOS
    dependencies:
      - target: Heptad-macOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: dev.lipovoy.heptad.mac.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Heptad.app/Contents/MacOS/Heptad"
  Heptad-iOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests/Shared
    dependencies:
      - target: Heptad-iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: dev.lipovoy.heptad.ios.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Heptad.app/Heptad"
